# Generated by Django 2.2 on 2019-04-11 11:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAreaLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAreaLevel5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubLocalityLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubLocalityLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubLocalityLevel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubLocalityLevel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubLocalityLevel5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('long_name_en', models.CharField(max_length=50, null=True)),
                ('long_name_ru', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=50)),
                ('short_name_en', models.CharField(max_length=50, null=True)),
                ('short_name_ru', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('formatted_address', models.CharField(max_length=250)),
                ('formatted_address_en', models.CharField(max_length=250, null=True)),
                ('formatted_address_ru', models.CharField(max_length=250, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street_number', models.CharField(blank=True, max_length=10)),
                ('street_number_en', models.CharField(blank=True, max_length=10, null=True)),
                ('street_number_ru', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('floor_en', models.CharField(blank=True, max_length=10, null=True)),
                ('floor_ru', models.CharField(blank=True, max_length=10, null=True)),
                ('room', models.CharField(blank=True, max_length=10)),
                ('room_en', models.CharField(blank=True, max_length=10, null=True)),
                ('room_ru', models.CharField(blank=True, max_length=10, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('administrative_area_level_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.AdministrativeAreaLevel1')),
                ('administrative_area_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.AdministrativeAreaLevel2')),
                ('administrative_area_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.AdministrativeAreaLevel3')),
                ('administrative_area_level_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.AdministrativeAreaLevel4')),
                ('administrative_area_level_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.AdministrativeAreaLevel5')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Locality')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Neighborhood')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Route')),
                ('sublocality_level_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.SubLocalityLevel1')),
                ('sublocality_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.SubLocalityLevel2')),
                ('sublocality_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.SubLocalityLevel3')),
                ('sublocality_level_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.SubLocalityLevel4')),
                ('sublocality_level_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.SubLocalityLevel5')),
            ],
        ),
    ]
