# Generated by Django 2.2.4 on 2019-08-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
    ]
