# Generated by Django 2.2.4 on 2019-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_auto_20190827_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_id",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
