# Generated by Django 2.2.5 on 2019-09-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_auto_20190828_0727"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativearealevel1",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel1",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel2",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel2",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel3",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel3",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel4",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel4",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel5",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="administrativearealevel5",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="locality",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="locality",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="floor_es",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="formatted_address_es",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="room_es",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="street_number_es",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel1",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel1",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel2",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel2",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel3",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel3",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel4",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel4",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel5",
            name="long_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sublocalitylevel5",
            name="short_name_es",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
